name: Publish Package

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - uses: dotnet/nbgv@master
        id: nbgv
      - name:  Publish package to nuget.org
        id: publish_nuget
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: Starknet.Voyager/Starknet.Voyager.csproj
          NUGET_KEY: ${{ steps.nbgv.outputs.NuGetPackageVersion }}
          VERSION_STATIC: $GITVERSION_NUGETVERSIONV2