name: Unit Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore Starknet.Voyager dependencies
      run: dotnet restore Starknet.Voyager
    - name: Build Starknet.Voyager
      run: dotnet build Starknet.Voyager --no-restore
    - name: Restore Starknet.Voyager.UnitTests dependencies
      run: dotnet restore Starknet.Voyager.UnitTests
    - name: Build Starknet.Voyager.UnitTests
      run: dotnet build Starknet.Voyager.UnitTests --no-restore
    - name: Unit Test
      run: dotnet test Starknet.Voyager.UnitTests --logger:"xunit;LogFilePath=test_result.xml" --collect:"XPlat Code Coverage" --no-build --verbosity normal
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: Starknet.Voyager.UnitTests/test_result.xml
    - name: Find and Move Coverage XML
      run: |
        xml_path=$(find "$(pwd -P)" -name "coverage.cobertura.xml")
        mv "$xml_path" Starknet.Voyager.UnitTests/
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.25
      with:
        reports: Starknet.Voyager.UnitTests/coverage.cobertura.xml
        targetdir: coveragereport
    - name: Install html2text
      run: sudo apt install html2text
    - name: Parse coverage report
      run: |
        cd coveragereport
        html2text index.html